### ISSUE TITLE
Theme Command

### ISSUE THREAD

**Issue by EmiSu9999** [japanoise/tewibot#3]
A command that sets a theme for a character using &theme [song url] [character name] and retrieves the url through &theme [character name] pulling up an embed of the url, or lists all your families themes (possibly without the embeds of the url, if possible) if no character is specified

**Comment by japanoise** [comment]
(just copypasting some notes, ignore me)

1. detect whether word 1 starts with http:// or https:// if it does then set it, else get it
2. remember to update getFamily
3. Compare: waifuPicAdd getWaifuPic
4. https://github.com/japanoise/tewibot/blob/master/main.go#L49 add a field Theme string here (it needs to be capitalised like that so that it serializes)
